insert into Categoria values(1 ,"Pizzas"),(2 ,"Pastas "),(3 ,"Carnes"),(4 ,"Vegeteariano"),(5 ,"Vegano"),(6,"Otros"),(7,"Postres"),(8,"Entradas"),(9,"Acompañamientos");
insert into Producto values(101,"Asado",2500,"Carne de vaca, cerdo, chivo","https://media.istockphoto.com/id/1219721088/es/foto/surtido-de-deliciosa-carne-a-la-parrilla-en-una-barbacoa.jpg?s=612x612&w=0&k=20&c=3-VoT6Htww9W2WQWnyfDrCJTrQr12RNqbnmSVjt7uAE=","Un clásico argentino, consiste en cortes de carne de res, como el bife de chorizo y las costillas, cocinados a la parrilla con brasas de leña para obtener un sabor ahumado y jugoso.",3),
(102,"Doc.Empanadas",2600,"a eleccion","https://media.istockphoto.com/id/521954007/es/foto/pollo-relleno-de-empanadas-casera.jpg?s=612x612&w=0&k=20&c=QPCkMlIwKatscw6tpnsMQVD9-lx7wOpxmZqpzWK3vkQ=","Deliciosas empanadas argentinas rellenas de carne, pollo, jamón y queso, espinacas o queso y cebolla, envueltas en una masa crujiente y horneadas u fritas",6),
(103,"Milanesa",2500,"Carne-Pollo,Elec.Guar.","https://media.istockphoto.com/id/1057832572/es/foto/tradicional-italiano-ternera-milanesa-con-lim%C3%B3n-y-papas-fritas-cerca-vista-superior-horizontal.jpg?s=612x612&w=0&k=20&c=6qSaRfmYe_F_jElUBTm9xdyNyO0Trgl02ZDquIoEY-k=","Una fina y tierna milanesa de carne de res empanizada, acompañada de papas fritas o puré de papas. Puede ser de ternera o de pollo",3),
(104,"Provoleta",1000,"Queso","https://media.istockphoto.com/id/1262349315/es/foto/provoleta-argentina.jpg?s=612x612&w=0&k=20&c=-Y4wJtcvPt7sGVAE3EQ3vm8kgTugSl2K80PEcL_e7Yw=","Un plato de queso provolone derretido a la parrilla, servido con aceite de oliva, orégano y ajo. Se derrite hasta que se forme una capa dorada y se sirve caliente.",6),
(105,"Locro",2000,"maiz blanco, porortos, chorizo,cebolla,puerro,calabaza,morrron","https://media.istockphoto.com/id/1174342331/es/foto/locro-con-pastelito.jpg?s=612x612&w=0&k=20&c=pYq1NO6RseFNal0mgVOix3iN-T8XFJPB1zdVcmorCW4=","Un guiso tradicional argentino hecho a base de maíz, carne de cerdo, chorizo, porotos, zapallo (calabaza) y especias. Es un plato sustancioso y reconfortante, especialmente popular durante las celebraciones patrias.",6),
(106,"Matambre",1300,"Carne","https://media.istockphoto.com/id/1188694320/es/foto/pieza-asada-sazonada-de-matambre-de-cerdo-vientre-de-cerdo-argentino-sobre-tabla-de-madera.jpg?s=612x612&w=0&k=20&c=L3LBSRIAgLg5R678lcdRso-non6AqhzcfikLYokkU54=","Un rollo de carne de res relleno con una mezcla de verduras, huevos duros, aceitunas y condimentos, luego se cocina al horno o a la parrilla. Se sirve en rodajas finas y se puede comer solo o en sándwiches",3),
(107,"Choripan",1200,"Chorizo","https://media.istockphoto.com/id/1318927305/es/foto/choripan-argentino-con-chimichurri-y-salsa-criolla.jpg?s=612x612&w=0&k=20&c=PnY1WWLHEWzYGFcVrdzchPAfql9v_QTflQ_KCgOTfw8=","Un clásico argentino de la comida callejera, consiste en una salchicha de chorizo a la parrilla servida en un pan fresco. Se puede acompañar con chimichurri, salsa criolla o salsa picante.",3),
(707,"Pastel de papa",3000,"Papas,carne picada","https://media.istockphoto.com/id/154280601/es/foto/tartas-pastel-de-papas.jpg?s=612x612&w=0&k=20&c=7jbC6wht0-aFX9fDBCkJVcfxtert1I5SBWhjsSzYbao=","Un plato reconfortante hecho con capas de puré de papas suave y cremoso, carne picada y condimentos, horneado hasta que se dore. Es una especie de pastel de carne, pero con base de papa.",3),
(108,"Milanesa napolitana",2000,"Milanesa de Ternera/ Pollo, Tomate, Mozzarela,Jamon","https://media.istockphoto.com/id/506065396/es/foto/milanesa-napolitana-y-ensaladas-con-zanahoria-huevo.jpg?s=612x612&w=0&k=20&c=ByXJ_yJjFtw3f85h_Eqlb1mGDQmZjjpj14vUhCpIQEo=","Un filete de carne empanizado y frito, generalmente de ternera, cubierto con una salsa de toma rodajas de mozzarella derretida y hojas de albahaca fresa",3),
(109,"Lasagna alla bolognese",1800,"Pasta,Quese ricota, Mozzarella,Carne picada","https://media.istockphoto.com/id/1252736340/es/foto/lasa%C3%B1a-pasta-tradicional-italiana.jpg?s=612x612&w=0&k=20&c=0o5pJXx3DLYEf_1NayR-DVHXz8fnI1nce-VBS1bpKUo=","Capas de pasta fresca intercaladas con una rica salsa de carne boloñesa, queso ricotta y mozzarella, horneadas hasta obtener una deliciosa y reconfortante cazuela.",2),
(110,"Risotto ai Funghi Porcini",1900,"Arroz,Caldo de verduras,Hongos, Queso parmesano","https://media.istockphoto.com/id/1178746861/es/foto/risotto-ai-funghi-arroz-con-setas-con-ingredientes-sobre-un-fondo-r%C3%BAstico-oscuro-de-madera.jpg?s=612x612&w=0&k=20&c=2MMoL61dUl1zU5gJKLUFd_oKMnv8y8I3zpxlx9alKDg=","Un cremoso risotto preparado con arroz arbóreo, caldo de verduras y los sabrosos hongos porcini, complementado con un toque de parmesano rallado.",2),
(111,"Tagliatelle al Ragù",1870,"Tallarines,Salsa Ragu, Tomates,Zanahorias,apio y Vino tinto","https://media.istockphoto.com/id/1277134519/es/foto/cena-italiana-tagliatelle-de-pasta-de-huevo-con-salsa-bolo%C3%B1esa-hecha-de-carne-y-salsa-de.jpg?s=612x612&w=0&k=20&c=93HUDk_3Od0S9R2st58wd3nEcYCXIDbnf4F-fdgQ54U=","Fideos frescos alargados, hechos a mano, acompañados de una salsa de ragú de carne, lentamente cocinada con tomates, zanahorias, apio y vino tinto.",2),
(112,"Pizza Margherita",2560,"Pizza,Salsa de tomate,Mozzarella,Albahaca","https://media.istockphoto.com/id/1098003566/es/foto/italian-pizza-margherita-con-tomates-y-queso-mozzarella-en-tabla-de-cortar-madera-cierre-para.jpg?s=612x612&w=0&k=20&c=riumuNLBUYrs_OwHDqFL9WybthO5Z3q7PLSIXCtODCs=","Una clásica pizza italiana con una base de masa fina y crujiente, cubierta con tomate fresco, mozzarella de búfala y hojas de albahaca, creando una combinación simple pero sabrosa.",1),
(113,"Osso Buco alla Milanese",1870,"Carne,Guiso,Vino blanco,Caldo,Zanahorias,Apio y Cebolla","https://media.istockphoto.com/id/1395060551/es/foto/plato-tradicional-italiano-osso-buco-con-risotto-milan%C3%A9s-y-tomate-cherry-y-rucola-ossobuco-con.jpg?s=612x612&w=0&k=20&c=O5n5MBecPcRPc0jM2L6YMD5ERASA7UEFGwIvwbtq2kQ=","Tiernos trozos de carne de ternera, cocinados lentamente en un guiso con vino blanco, caldo de carne, zanahorias, apio y cebolla, servidos con una guarnición de risotto al azafrán.",6),
(114,"Spaghetti alla Carbonara",1970,"Spaghetti, Salsa cremosa,Panceta,Queso pecorino romano y Pimienta negra","https://media.istockphoto.com/id/95616888/es/foto/siga-con-unos-fetuchini-carbonara.jpg?s=612x612&w=0&k=20&c=LD3Vec3CS5Ctj8sHyZH0RJa-WpvvKgERImxmQeuV-ho=","Espaguetis al dente, mezclados con una salsa cremosa hecha de yemas de huevo, panceta salteada, queso pecorino romano y un toque de pimienta negra.",2),
(115,"Caprese",1650,"Tomate, Mozzarella,Albahaca","https://media.istockphoto.com/id/1350512852/es/foto/se-sirve-ensalada-italiana-caprese-y-salsa-pesto-entrante-gourmet-antipasto-vegetariano.jpg?s=612x612&w=0&k=20&c=ksBOJgMYzwj6ysfw7_MvfPwl7dW6XGIbObErBoDDvJ8=","Una ensalada fresca y colorida compuesta por rodajas de tomate maduro, mozzarella de búfala y hojas de albahaca, sazonada con aceite de oliva virgen extra y un toque de sal.",4),
(116,"Pollo alla Cacciatora",1700," Trozos de pollo,una salsa de tomate,cebolla,ajo, pimientos, aceitunas, vino blanco","https://media.istockphoto.com/id/1195033137/es/foto/cacciatore-de-pollo-con-pechugas-de-pollo-tiernas-tomates-pimientos-zanahorias-y-champi%C3%B1ones.jpg?s=612x612&w=0&k=20&c=IbE8Jxkw1TDaPjPkWHywtgbL6fqSi7o8US6IfY9AQnI=","Trozos de pollo dorados, cocinados en una salsa de tomate con cebolla, ajo, pimientos, aceitunas, vino blanco y hierbas aromáticas, creando un plato sabroso y reconfortante.",3),
(117,"Gelato",950,"Sabor a Eleccion, preguntar","https://media.istockphoto.com/id/849782264/es/foto/tres-bolas-de-helado-de-stracciatella-italiano.jpg?s=612x612&w=0&k=20&c=Pk9uIXLkb_VfW6JfffT__DIZO1nLmUi-fs4HzygtF1s=","El helado italiano tradicionalmente preparado con ingredientes frescos y naturales, con una textura suave y cremosa. Disponible en una amplia variedad de sabores, desde el clásico de vainilla hasta los más exóticos como pistacho o stracciatella.",7),
(118,"Tiramisú",2100,"Crema mascarpone,Cacao,Cognac,Bizcocho","https://media.istockphoto.com/id/1351167325/es/foto/postres-tradicionales-italianos-tiramis%C3%BA-y-cannoli-en-el-plato.jpg?s=612x612&w=0&k=20&c=tG28ihzqkNDUbw8_xzkpQ7GXlbYzYGttOeBI5JJrR_U=","Un postre italiano clásico y tentador, compuesto por capas de bizcocho de café empapado, crema de mascarpone y espolvoreado con cacao en polvo.",7),
(119,"El cannolo",1500,"Harina de trigo,Cacao","https://media.istockphoto.com/id/482479948/es/foto/cannoli.jpg?s=612x612&w=0&k=20&c=fPoRoXjC9X1jnhwVVbG8bsqiKyzu03eoPHB4sANEjQ0=","Es un dulce típico de la región italiana de Sicilia, de donde es originario. Consiste en una masa enrollada en forma de tubo que dentro lleva ingredientes mezclados con queso ricota.",7),
(120,"Alfajores",1450,"Harina,Maicena,Dulce de Leche, Coco rallado","https://media.istockphoto.com/id/1180243264/es/foto/alfajores-argentinos-tradicionales.jpg?s=612x612&w=0&k=20&c=twBFtEiO9sf5wH9IkLQyoCZMNHw1pJHBHZ8HwzmZ14k=","Dulces argentinos compuestos por dos galletas suaves y dulces, generalmente de maicena, rellenas de dulce de leche y, a veces, cubiertas de chocolate o espolvoreadas con coco rallado.",7),

(121,"Pizza Marinara",2560,"Pizza,Salsa de tomate, ajo, oregano, aceite de oliva, aceitunas negras","https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/97C2C718-5015-437F-8355-316EE000F57C/Derivates/556409BB-02E0-4BA3-BC16-F409F609FCED.jpg","La pizza Marinara también es bastante simple y está hecha con salsa de tomate, ajo, orégano, aceite de oliva y a veces se le añaden algunas aceitunas negras.",1),
(122,"Pizza Napolitana",2560,"Pizza,Tomate, Mozzarella,Albahaca fresca, aceite de oliva","https://s1.abcstatics.com/media/gurme/2022/11/23/s/pizza-napolitana-kt9E--1200x630@abc.jpg","Esta es una variedad de pizza muy tradicional de Nápoles. Suele llevar tomate, mozzarella de búfala, albahaca fresca y aceite de oliva. La masa es fina y se hornea en un horno de leña.",1),
(123,"Pizza Diavola",2600,"Pizza,Salsa de tomate, Mozzarella y Salame picate","https://www.iffco.it/sites/default/files/styles/free_crop/public/img/recipe/gran-cucina-pizza-diavola.jpg?h=de92a0b7&itok=eC0EvTVI","Esta pizza es conocida por su toque picante. Está hecha con salsa de tomate, mozzarella y salame picante.",1),
(124,"Pizza Quattro Stagioni",2900,"Pizza, Alcachofas, Jamon,Champiñones y Aceitunas negras","https://www.bettybossi.ch/rdbimg/bb_bbzc220315_0015a/bb_bbzc220315_0015a_r02_v003_x0020.jpg","Esta pizza se divide en cuatro secciones, cada una con ingredientes que representan una estación del año. Las secciones incluyen alcachofas, jamón, champiñones y aceitunas negras.",1),
(125,"Pizza Romana",2700,"Pizza,Tomate,Mozzarella,Aceite de oliva y albahaca fresca","https://blogger.googleusercontent.com/img/a/AVvXsEgxqpDt3fozZHwuevAPApvA6kzoPF4HFvnAIBMFqYKhi_BZqHtrpgdu5W9Rg3o0EKZ1iD6ru_vkgwGKIDt2vK9YLxwIkYW999NvAI7VTi8KITsh6WgWVMZbgpkVI7NeBeBqwbqxZdPZn_m5hGqgVTK2ePJoQ5DDO_738K2PaTh86aDFtq_GfEsbubsP=s16000","La pizza Romana tiene una base muy fina y crujiente. Se cubre con ingredientes como tomate, mozzarella, aceite de oliva y albahaca fresca",1),

(126,"Ravioli con Mantequilla y Salvia",2300,"Queso, Carne o Espinacas, Salsa de Manteca, Hojas de salvia","https://saboraitaliamx.com/wp-content/uploads/2020/08/Ravioli.jpg","Ravioli rellenos de queso, carne o espinacas, servidos con una salsa de mantequilla derretida y hojas de salvia crujientes",2),
(127,"Gnocchi alla Sorrentina",2500,"Papa,Salsa de tomate,Mozzarella,Albahaca","https://saboraitaliamx.com/wp-content/uploads/2020/10/shutterstock_543388549-scaled.jpg"," Gnocchi, pequeñas bolas de pasta de patata, cubiertos con salsa de tomate, mozzarella y albahaca, y horneados hasta que el queso se derrite y burbujea",2),
(128,"Pappardelle al Cinghiale",2500,"Salsa de jabali,Pasta ancha","https://media.istockphoto.com/id/970979140/it/foto/pappardelle-con-rag%C3%B9-di-cinghiale-ricetta-tipica-toscana.jpg?s=612x612&w=0&k=20&c=Y020ci50HUVNeMdaL0VkZnhlwQs4wzAzaFNPamTUMcc=","Pappardelle, pasta ancha, servida con una salsa de jabalí, una preparación típica de la Toscana.",2);

update Producto set Categoria_idCategoria=3 where idProducto=113;
select  * from Categoria;
select * from Producto;